version: '3.4'

services:
  04:
    image: 04
    build:
      context: Fundamentals-HandsOn/L10-03 Push Express site to Docker Hub
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
